version: "3.9"

services:
  neuravis:
    build: .
    container_name: neuravis_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./media:/app/media
      - ./animations:/app/animations
    restart: unless-stopped
